server:
  port: 18080

spring:
  application:
    name: lc4j_02_multi_model

logging:
  level:
    '[dev.langchain4j]': DEBUG

llm:
  dashscope:
    api-key: ${DASHSCOPE_API}
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    default-model: qwen-plus
  deepseek:
    default-model: deepseek-v3.1