server:
  port: 18080

spring:
  application:
    name: lc4j_02_multi_model

langchain4j:
  open-ai:
    chat-model:
      api-key: ${DASHSCOPE_API}
      model-name: qwen-plus
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true

logging:
  level:
    '[dev.langchain4j]': DEBUG
